import { PrismaClient, Gender } from '@prisma/client';

export async function seedFacultyProfiles(prisma: PrismaClient): Promise<void> {
  console.log('  🌱 Seeding faculty profiles...');

  const profiles = [
    {
      email: 'arjun.mehta@college.edu',
      employeeId: 'EMP001', designation: 'Professor',
      department: 'Computer Science & Engineering',
      qualification: 'PhD (IIT Bombay), M.Tech, B.E',
      specialization: 'Machine Learning, Deep Learning, Computer Vision',
      experienceYears: 18, gender: Gender.MALE,
      phone: '9876543201', orcidId: '0000-0001-2345-6789',
      googleScholarUrl: 'https://scholar.google.com/citations?user=arjunmehta',
      scopusId: 'SC-001234', isHod: true,
      researchInterests: ['Deep Learning','Neural Networks','Computer Vision','NLP'],
      bio: 'Dr. Arjun Mehta is a Professor and Head of Department of CSE with over 18 years of experience in teaching and research.',
      dateOfJoining: new Date('2006-07-01'), dateOfBirth: new Date('1975-03-15'),
    },
    {
      email: 'priya.nair@college.edu',
      employeeId: 'EMP002', designation: 'Associate Professor',
      department: 'Electronics & Communication Engineering',
      qualification: 'PhD (NIT Calicut), M.Tech, B.Tech',
      specialization: 'VLSI Design, Embedded Systems, IoT',
      experienceYears: 14, gender: Gender.FEMALE,
      phone: '9876543202', orcidId: '0000-0002-3456-7890',
      googleScholarUrl: 'https://scholar.google.com/citations?user=priyanair',
      scopusId: 'SC-002345',
      researchInterests: ['VLSI Design','Embedded Systems','IoT','Signal Processing'],
      bio: 'Dr. Priya Nair specializes in VLSI design and has published over 25 research papers in international journals.',
      dateOfJoining: new Date('2010-07-15'), dateOfBirth: new Date('1980-06-22'),
    },
    {
      email: 'suresh.rao@college.edu',
      employeeId: 'EMP003', designation: 'Professor',
      department: 'Mechanical Engineering',
      qualification: 'PhD (IISc), M.E, B.E',
      specialization: 'Thermal Engineering, Fluid Mechanics, CFD',
      experienceYears: 22, gender: Gender.MALE,
      phone: '9876543203',
      researchInterests: ['Thermal Engineering','Fluid Mechanics','CFD','Heat Transfer'],
      bio: 'Prof. Suresh Rao has extensive experience in thermal engineering research.',
      dateOfJoining: new Date('2002-06-01'), dateOfBirth: new Date('1970-11-08'),
    },
    {
      email: 'deepa.krishnan@college.edu',
      employeeId: 'EMP004', designation: 'Assistant Professor',
      department: 'Computer Science & Engineering',
      qualification: 'PhD (Anna University), M.Tech, B.E',
      specialization: 'Data Science, Big Data Analytics, Cloud Computing',
      experienceYears: 9, gender: Gender.FEMALE,
      phone: '9876543204', orcidId: '0000-0003-4567-8901',
      researchInterests: ['Data Science','Big Data','Cloud Computing','Distributed Systems'],
      bio: 'Dr. Deepa Krishnan is an enthusiastic researcher in data science and cloud computing.',
      dateOfJoining: new Date('2015-08-01'), dateOfBirth: new Date('1985-09-14'),
    },
    {
      email: 'rajiv.sharma@college.edu',
      employeeId: 'EMP005', designation: 'Professor',
      department: 'Electrical Engineering',
      qualification: 'PhD (IIT Delhi), M.Tech, B.Tech',
      specialization: 'Power Systems, Renewable Energy, Smart Grid',
      experienceYears: 20, gender: Gender.MALE,
      phone: '9876543205', scopusId: 'SC-003456',
      researchInterests: ['Power Systems','Renewable Energy','Smart Grid','Power Electronics'],
      bio: 'Dr. Rajiv Sharma is a leading researcher in renewable energy systems.',
      dateOfJoining: new Date('2004-07-01'), dateOfBirth: new Date('1972-01-30'),
    },
    {
      email: 'anita.desai@college.edu',
      employeeId: 'EMP006', designation: 'Associate Professor',
      department: 'Information Technology',
      qualification: 'PhD (Pune University), MCA, BCA',
      specialization: 'Cybersecurity, Network Security, Blockchain',
      experienceYears: 12, gender: Gender.FEMALE,
      phone: '9876543206',
      researchInterests: ['Cybersecurity','Network Security','Blockchain','Cryptography'],
      bio: 'Prof. Anita Desai is an expert in cybersecurity and blockchain technology.',
      dateOfJoining: new Date('2012-07-16'), dateOfBirth: new Date('1982-04-07'),
    },
    {
      email: 'vikram.singh@college.edu',
      employeeId: 'EMP007', designation: 'Professor',
      department: 'Civil Engineering',
      qualification: 'PhD (IIT Roorkee), M.Tech, B.E',
      specialization: 'Structural Engineering, Earthquake Engineering',
      experienceYears: 16, gender: Gender.MALE,
      phone: '9876543207',
      researchInterests: ['Structural Engineering','Earthquake Engineering','Concrete Technology'],
      bio: 'Dr. Vikram Singh is a structural engineering expert with focus on earthquake-resistant design.',
      dateOfJoining: new Date('2008-08-01'), dateOfBirth: new Date('1977-07-19'),
    },
    {
      email: 'meena.iyer@college.edu',
      employeeId: 'EMP008', designation: 'Assistant Professor',
      department: 'Electronics & Communication Engineering',
      qualification: 'PhD (BITS Pilani), M.Tech, B.Tech',
      specialization: 'Signal Processing, Wireless Communication, 5G',
      experienceYears: 7, gender: Gender.FEMALE,
      phone: '9876543208', orcidId: '0000-0004-5678-9012',
      researchInterests: ['Signal Processing','5G Networks','Wireless Communication','Antenna Design'],
      bio: 'Dr. Meena Iyer focuses on 5G wireless communication and signal processing.',
      dateOfJoining: new Date('2017-07-01'), dateOfBirth: new Date('1988-12-03'),
    },
    {
      email: 'ashok.patel@college.edu',
      employeeId: 'EMP009', designation: 'Professor',
      department: 'Mechanical Engineering',
      qualification: 'PhD (IIT Madras), M.Tech, B.Tech',
      specialization: 'Manufacturing, CAD/CAM, Robotics',
      experienceYears: 19, gender: Gender.MALE,
      phone: '9876543209',
      researchInterests: ['Manufacturing','CAD/CAM','Robotics','Automation'],
      bio: 'Prof. Ashok Patel has wide expertise in advanced manufacturing technologies.',
      dateOfJoining: new Date('2005-06-01'), dateOfBirth: new Date('1974-05-28'),
    },
    {
      email: 'lavanya.subramanian@college.edu',
      employeeId: 'EMP010', designation: 'Associate Professor',
      department: 'Computer Science & Engineering',
      qualification: 'PhD (VIT University), M.Tech, B.Tech',
      specialization: 'Artificial Intelligence, Robotics, Computer Vision',
      experienceYears: 11, gender: Gender.FEMALE,
      phone: '9876543210', orcidId: '0000-0005-6789-0123',
      scopusId: 'SC-004567',
      researchInterests: ['AI','Robotics','Computer Vision','Human-Robot Interaction'],
      bio: 'Dr. Lavanya Subramanian works on AI-driven robotics and human-robot interaction.',
      dateOfJoining: new Date('2013-07-01'), dateOfBirth: new Date('1983-08-16'),
    },
    {
      email: 'ravi.varma@college.edu',
      employeeId: 'EMP011', designation: 'Professor',
      department: 'Electrical Engineering',
      qualification: 'PhD (IIT Kharagpur), M.E, B.E',
      specialization: 'Control Systems, Industrial Automation',
      experienceYears: 21, gender: Gender.MALE,
      phone: '9876543211',
      researchInterests: ['Control Systems','Industrial Automation','PLC','SCADA'],
      dateOfJoining: new Date('2003-08-01'), dateOfBirth: new Date('1971-02-11'),
    },
    {
      email: 'sneha.gupta@college.edu',
      employeeId: 'EMP012', designation: 'Assistant Professor',
      department: 'Information Technology',
      qualification: 'PhD (Delhi University), M.Tech, B.Tech',
      specialization: 'Machine Learning, Natural Language Processing',
      experienceYears: 6, gender: Gender.FEMALE,
      phone: '9876543212',
      researchInterests: ['Machine Learning','NLP','Text Mining','Sentiment Analysis'],
      dateOfJoining: new Date('2018-07-01'), dateOfBirth: new Date('1990-10-25'),
    },
    {
      email: 'naresh.joshi@college.edu',
      employeeId: 'EMP013', designation: 'Associate Professor',
      department: 'Civil Engineering',
      qualification: 'PhD (MNIT Jaipur), M.Tech, B.E',
      specialization: 'Environmental Engineering, Water Resources',
      experienceYears: 13, gender: Gender.MALE,
      phone: '9876543213',
      researchInterests: ['Environmental Engineering','Water Treatment','Hydrology'],
      dateOfJoining: new Date('2011-08-01'), dateOfBirth: new Date('1981-03-20'),
    },
    {
      email: 'kavita.reddy@college.edu',
      employeeId: 'EMP014', designation: 'Professor',
      department: 'Electronics & Communication Engineering',
      qualification: 'PhD (Osmania University), M.Tech, B.Tech',
      specialization: 'Microelectronics, Photonics, Nanotechnology',
      experienceYears: 17, gender: Gender.FEMALE,
      phone: '9876543214', scopusId: 'SC-005678',
      researchInterests: ['Microelectronics','Photonics','Nanotechnology','Semiconductor Devices'],
      dateOfJoining: new Date('2007-07-01'), dateOfBirth: new Date('1976-09-04'),
    },
    {
      email: 'mohan.das@college.edu',
      employeeId: 'EMP015', designation: 'Associate Professor',
      department: 'Mechanical Engineering',
      qualification: 'PhD (NIT Trichy), M.Tech, B.E',
      specialization: 'Material Science, Composite Materials',
      experienceYears: 15, gender: Gender.MALE,
      phone: '9876543215',
      researchInterests: ['Material Science','Composite Materials','Nano-composites'],
      dateOfJoining: new Date('2009-07-01'), dateOfBirth: new Date('1979-06-17'),
    },
    {
      email: 'shantha.pillai@college.edu',
      employeeId: 'EMP016', designation: 'Professor',
      department: 'Computer Science & Engineering',
      qualification: 'PhD (Kerala University), M.Tech, B.Tech',
      specialization: 'Operating Systems, Distributed Computing, Cloud',
      experienceYears: 20, gender: Gender.FEMALE,
      phone: '9876543216', orcidId: '0000-0006-7890-1234',
      researchInterests: ['Operating Systems','Distributed Computing','Cloud Infrastructure'],
      dateOfJoining: new Date('2004-08-01'), dateOfBirth: new Date('1973-11-22'),
    },
    {
      email: 'arun.kumar@college.edu',
      employeeId: 'EMP017', designation: 'Assistant Professor',
      department: 'Information Technology',
      qualification: 'PhD (SRM University), M.Tech, B.Tech',
      specialization: 'Internet of Things, Edge Computing',
      experienceYears: 5, gender: Gender.MALE,
      phone: '9876543217',
      researchInterests: ['IoT','Edge Computing','Fog Computing','Smart Cities'],
      dateOfJoining: new Date('2019-07-01'), dateOfBirth: new Date('1992-07-08'),
    },
    {
      email: 'divya.menon@college.edu',
      employeeId: 'EMP018', designation: 'Associate Professor',
      department: 'Electrical Engineering',
      qualification: 'PhD (Amrita University), M.Tech, B.Tech',
      specialization: 'Power Electronics, Electric Vehicles',
      experienceYears: 10, gender: Gender.FEMALE,
      phone: '9876543218',
      researchInterests: ['Power Electronics','Electric Vehicles','Battery Technology'],
      dateOfJoining: new Date('2014-07-01'), dateOfBirth: new Date('1984-04-30'),
    },
    {
      email: 'sanjay.bhatt@college.edu',
      employeeId: 'EMP019', designation: 'Professor',
      department: 'Civil Engineering',
      qualification: 'PhD (IIT Guwahati), M.Tech, B.E',
      specialization: 'Transportation Engineering, Highway Design',
      experienceYears: 18, gender: Gender.MALE,
      phone: '9876543219',
      researchInterests: ['Transportation Engineering','Highway Design','Pavement Design'],
      dateOfJoining: new Date('2006-08-01'), dateOfBirth: new Date('1976-12-14'),
    },
    {
      email: 'rekha.pandey@college.edu',
      employeeId: 'EMP020', designation: 'Assistant Professor',
      department: 'Computer Science & Engineering',
      qualification: 'PhD (JNTU Hyderabad), M.Tech, B.Tech',
      specialization: 'Computer Networks, Software Defined Networking',
      experienceYears: 8, gender: Gender.FEMALE,
      phone: '9876543220',
      researchInterests: ['Computer Networks','SDN','Network Virtualization','5G'],
      dateOfJoining: new Date('2016-07-01'), dateOfBirth: new Date('1987-02-18'),
    },
    {
      email: 'girish.nanda@college.edu',
      employeeId: 'EMP021', designation: 'Professor',
      department: 'Mechanical Engineering',
      qualification: 'PhD (IIT Bombay), M.Tech, B.Tech',
      specialization: 'Automotive Engineering, Vehicle Dynamics',
      experienceYears: 23, gender: Gender.MALE,
      phone: '9876543221',
      researchInterests: ['Automotive Engineering','Vehicle Dynamics','NVH','FEM'],
      dateOfJoining: new Date('2001-08-01'), dateOfBirth: new Date('1969-08-27'),
    },
    {
      email: 'usha.venkat@college.edu',
      employeeId: 'EMP022', designation: 'Associate Professor',
      department: 'Electronics & Communication Engineering',
      qualification: 'PhD (Manipal University), M.Tech, B.Tech',
      specialization: 'Biomedical Engineering, Medical Image Processing',
      experienceYears: 14, gender: Gender.FEMALE,
      phone: '9876543222', orcidId: '0000-0007-8901-2345',
      researchInterests: ['Biomedical Engineering','Medical Imaging','Healthcare IoT'],
      dateOfJoining: new Date('2010-08-01'), dateOfBirth: new Date('1980-01-05'),
    },
    {
      email: 'pramod.hegde@college.edu',
      employeeId: 'EMP023', designation: 'Professor',
      department: 'Information Technology',
      qualification: 'PhD (Mysore University), M.Tech, B.E',
      specialization: 'Database Systems, Data Warehousing, NoSQL',
      experienceYears: 19, gender: Gender.MALE,
      phone: '9876543223', scopusId: 'SC-006789',
      researchInterests: ['Database Systems','Data Warehousing','NoSQL','Graph Databases'],
      dateOfJoining: new Date('2005-07-01'), dateOfBirth: new Date('1974-10-09'),
    },
    {
      email: 'leela.narayan@college.edu',
      employeeId: 'EMP024', designation: 'Associate Professor',
      department: 'Civil Engineering',
      qualification: 'PhD (CEPT University), M.Tech, B.E',
      specialization: 'Geotechnical Engineering, Foundation Design',
      experienceYears: 12, gender: Gender.FEMALE,
      phone: '9876543224',
      researchInterests: ['Geotechnical Engineering','Foundation Design','Soil Mechanics'],
      dateOfJoining: new Date('2012-08-01'), dateOfBirth: new Date('1982-05-21'),
    },
    {
      email: 'dilip.shetty@college.edu',
      employeeId: 'EMP025', designation: 'Assistant Professor',
      department: 'Computer Science & Engineering',
      qualification: 'PhD (Mangalore University), M.Tech, B.E',
      specialization: 'Quantum Computing, Cryptography',
      experienceYears: 6, gender: Gender.MALE,
      phone: '9876543225', orcidId: '0000-0008-9012-3456',
      researchInterests: ['Quantum Computing','Post-Quantum Cryptography','Algorithms'],
      dateOfJoining: new Date('2018-08-01'), dateOfBirth: new Date('1990-03-12'),
    },
    {
      email: 'aarti.saxena@college.edu',
      employeeId: 'EMP026', designation: 'Professor',
      department: 'Electrical Engineering',
      qualification: 'PhD (IIT Kanpur), M.Tech, B.Tech',
      specialization: 'High Voltage Engineering, Power Quality',
      experienceYears: 16, gender: Gender.FEMALE,
      phone: '9876543226',
      researchInterests: ['High Voltage Engineering','Power Quality','Insulation Technology'],
      dateOfJoining: new Date('2008-07-01'), dateOfBirth: new Date('1977-07-23'),
    },
    {
      email: 'bhaskar.rao@college.edu',
      employeeId: 'EMP027', designation: 'Associate Professor',
      department: 'Mechanical Engineering',
      qualification: 'PhD (IIT Hyderabad), M.Tech, B.Tech',
      specialization: 'Additive Manufacturing, 3D Printing',
      experienceYears: 10, gender: Gender.MALE,
      phone: '9876543227',
      researchInterests: ['Additive Manufacturing','3D Printing','Bio-printing','Topology Optimization'],
      dateOfJoining: new Date('2014-08-01'), dateOfBirth: new Date('1984-11-16'),
    },
    {
      email: 'chitra.suresh@college.edu',
      employeeId: 'EMP028', designation: 'Professor',
      department: 'Electronics & Communication Engineering',
      qualification: 'PhD (PSG College of Technology), M.Tech, B.E',
      specialization: 'Antenna Design, RF Engineering, Radar',
      experienceYears: 17, gender: Gender.FEMALE,
      phone: '9876543228', scopusId: 'SC-007890',
      researchInterests: ['Antenna Design','RF Engineering','Radar Systems','Microwave'],
      dateOfJoining: new Date('2007-08-01'), dateOfBirth: new Date('1976-04-02'),
    },
    {
      email: 'devraj.malhotra@college.edu',
      employeeId: 'EMP029', designation: 'Associate Professor',
      department: 'Computer Science & Engineering',
      qualification: 'PhD (Thapar University), M.Tech, B.Tech',
      specialization: 'Software Engineering, DevOps, Agile Methods',
      experienceYears: 11, gender: Gender.MALE,
      phone: '9876543229',
      researchInterests: ['Software Engineering','DevOps','Agile','Software Testing'],
      dateOfJoining: new Date('2013-08-01'), dateOfBirth: new Date('1983-09-28'),
    },
    {
      email: 'esha.kulkarni@college.edu',
      employeeId: 'EMP030', designation: 'Assistant Professor',
      department: 'Information Technology',
      qualification: 'PhD (Savitribai Phule Pune University), M.Tech, B.E',
      specialization: 'Human-Computer Interaction, UX Research',
      experienceYears: 5, gender: Gender.FEMALE,
      phone: '9876543230', orcidId: '0000-0009-0123-4567',
      researchInterests: ['HCI','UX Research','Accessibility','Usability Testing'],
      dateOfJoining: new Date('2019-08-01'), dateOfBirth: new Date('1993-06-11'),
    },
  ];

  for (const profile of profiles) {
    const user = await prisma.user.findUnique({ where: { email: profile.email } });
    if (!user) continue;

    const { email, ...rest } = profile;

    await prisma.facultyProfile.upsert({
      where: { userId: user.id },
      update: {},
      create: { ...rest, userId: user.id },
    });
  }

  console.log('  ✅ Faculty profiles seeded: 30 profiles');
}
