import { PrismaClient, PatentStatus } from '@prisma/client';

export async function seedPatents(prisma: PrismaClient): Promise<void> {
  console.log('  🌱 Seeding patents...');

  const allFaculty = await prisma.facultyProfile.findMany({ include: { user: true } });
  const byEmail = Object.fromEntries(allFaculty.map(f => [f.user.email, f]));

  const patents = [
    { facultyEmail: 'arjun.mehta@college.edu',        title: 'Adaptive Deep Learning System for Real-Time Cyber Attack Detection in IoT Networks', applicationNo: 'IN202241078234', patentNo: null, filingDate: new Date('2022-11-15'), status: PatentStatus.PUBLISHED, inventors: ['Dr. Arjun Mehta','Dr. Deepa Krishnan'], country: 'India' },
    { facultyEmail: 'priya.nair@college.edu',          title: 'Reconfigurable Low Power VLSI Architecture for Multi-Standard Digital Signal Processing', applicationNo: 'IN202141056789', patentNo: 'IN398765', filingDate: new Date('2021-08-20'), grantDate: new Date('2023-03-10'), status: PatentStatus.GRANTED, inventors: ['Dr. Priya Nair'], country: 'India' },
    { facultyEmail: 'suresh.rao@college.edu',          title: 'Hybrid Nanofluid Based Enhanced Heat Exchanger for Solar Thermal Applications', applicationNo: 'IN202341089012', filingDate: new Date('2023-02-14'), status: PatentStatus.FILED, inventors: ['Prof. Suresh Rao','Prof. Ashok Patel'], country: 'India' },
    { facultyEmail: 'rajiv.sharma@college.edu',        title: 'Intelligent Energy Management System for Grid-Connected Microgrids with Renewable Sources', applicationNo: 'IN202041034567', patentNo: 'IN376543', filingDate: new Date('2020-06-30'), grantDate: new Date('2022-09-15'), status: PatentStatus.GRANTED, inventors: ['Dr. Rajiv Sharma','Prof. Divya Menon'], country: 'India' },
    { facultyEmail: 'anita.desai@college.edu',         title: 'Blockchain-Based Secure Data Sharing Framework for Healthcare Applications', applicationNo: 'IN202341091234', filingDate: new Date('2023-05-18'), status: PatentStatus.FILED, inventors: ['Prof. Anita Desai','Dr. Rekha Pandey'], country: 'India' },
    { facultyEmail: 'vikram.singh@college.edu',        title: 'Fiber Reinforced Polymer Composite Rebar with Enhanced Ductility for Earthquake-Resistant Structures', applicationNo: 'IN202141059876', patentNo: 'IN389012', filingDate: new Date('2021-10-25'), grantDate: new Date('2023-06-20'), status: PatentStatus.GRANTED, inventors: ['Dr. Vikram Singh'], country: 'India' },
    { facultyEmail: 'meena.iyer@college.edu',          title: 'Hybrid Beamforming Algorithm for Massive MIMO Systems in Millimeter Wave 5G Networks', applicationNo: 'IN202341095678', filingDate: new Date('2023-07-11'), status: PatentStatus.FILED, inventors: ['Dr. Meena Iyer','Dr. Chitra Suresh'], country: 'India' },
    { facultyEmail: 'ashok.patel@college.edu',         title: 'Smart Tooling System with Integrated Vibration Monitoring for CNC Machining Centers', applicationNo: 'IN202241076543', filingDate: new Date('2022-09-08'), status: PatentStatus.PUBLISHED, inventors: ['Prof. Ashok Patel'], country: 'India' },
    { facultyEmail: 'lavanya.subramanian@college.edu', title: 'Autonomous Robot Path Planning Algorithm Using Topological Map and Semantic Understanding', applicationNo: 'IN202341092345', filingDate: new Date('2023-04-03'), status: PatentStatus.FILED, inventors: ['Dr. Lavanya Subramanian','Dr. Arjun Mehta'], country: 'India' },
    { facultyEmail: 'ravi.varma@college.edu',          title: 'Model Predictive Controller for HVAC Systems with Occupancy-Based Adaptive Comfort Control', applicationNo: 'IN202141063456', patentNo: 'IN392341', filingDate: new Date('2021-12-10'), grantDate: new Date('2023-08-05'), status: PatentStatus.GRANTED, inventors: ['Dr. Ravi Varma'], country: 'India' },
    { facultyEmail: 'kavita.reddy@college.edu',        title: 'Metal Oxide Nanostructured Sensor Array for Simultaneous Detection of Multiple Toxic Gases', applicationNo: 'IN202241079876', filingDate: new Date('2022-11-30'), status: PatentStatus.PUBLISHED, inventors: ['Dr. Kavita Reddy'], country: 'India' },
    { facultyEmail: 'shantha.pillai@college.edu',      title: 'Energy-Efficient VM Consolidation and Migration Algorithm for Green Cloud Data Centers', applicationNo: 'IN202041038901', patentNo: 'IN368901', filingDate: new Date('2020-09-14'), grantDate: new Date('2022-12-01'), status: PatentStatus.GRANTED, inventors: ['Dr. Shantha Pillai','Dr. Pramod Hegde'], country: 'India' },
    { facultyEmail: 'naresh.joshi@college.edu',        title: 'Agricultural Waste Derived Biochar Composites for Heavy Metal Removal from Industrial Wastewater', applicationNo: 'IN202341094567', filingDate: new Date('2023-06-22'), status: PatentStatus.FILED, inventors: ['Dr. Naresh Joshi'], country: 'India' },
    { facultyEmail: 'mohan.das@college.edu',           title: 'Nano-Silica Reinforced Hybrid Polymer Composite with Superior Wear and Thermal Resistance', applicationNo: 'IN202141067890', patentNo: 'IN385432', filingDate: new Date('2021-09-05'), grantDate: new Date('2023-04-18'), status: PatentStatus.GRANTED, inventors: ['Prof. Mohan Das','Prof. Bhaskar Rao'], country: 'India' },
    { facultyEmail: 'divya.menon@college.edu',         title: 'Bidirectional Power Converter with SiC MOSFET for Fast Charging of Electric Vehicle Batteries', applicationNo: 'IN202241082345', filingDate: new Date('2022-10-07'), status: PatentStatus.PUBLISHED, inventors: ['Prof. Divya Menon','Dr. Rajiv Sharma'], country: 'India' },
    { facultyEmail: 'sanjay.bhatt@college.edu',        title: 'Crumb Rubber Modified Warm Mix Asphalt with Bio-Oil for Sustainable Road Pavement Construction', applicationNo: 'IN202341096789', filingDate: new Date('2023-08-15'), status: PatentStatus.FILED, inventors: ['Dr. Sanjay Bhatt'], country: 'India' },
    { facultyEmail: 'aarti.saxena@college.edu',        title: 'Dielectric Spectroscopy Based Condition Monitoring System for Oil-Immersed Power Transformers', applicationNo: 'IN202141071234', patentNo: 'IN381234', filingDate: new Date('2021-07-19'), grantDate: new Date('2023-02-28'), status: PatentStatus.GRANTED, inventors: ['Dr. Aarti Saxena'], country: 'India' },
    { facultyEmail: 'bhaskar.rao@college.edu',         title: 'Functionally Graded Lattice Structures for Bone Scaffold Fabrication Using Selective Laser Sintering', applicationNo: 'IN202241083456', filingDate: new Date('2022-12-19'), status: PatentStatus.PUBLISHED, inventors: ['Prof. Bhaskar Rao','Prof. Ashok Patel'], country: 'India' },
    { facultyEmail: 'chitra.suresh@college.edu',       title: 'Reconfigurable Frequency-Agile Antenna System for Multi-Band Wireless Communication Applications', applicationNo: 'IN202341097890', filingDate: new Date('2023-09-04'), status: PatentStatus.FILED, inventors: ['Dr. Chitra Suresh','Dr. Meena Iyer'], country: 'India' },
    { facultyEmail: 'dilip.shetty@college.edu',        title: 'Quantum-Resistant Cryptographic Protocol Using Lattice-Based Encryption for IoT Security', applicationNo: 'IN202341090123', filingDate: new Date('2023-03-27'), status: PatentStatus.FILED, inventors: ['Dr. Dilip Shetty'], country: 'India' },
    { facultyEmail: 'pramod.hegde@college.edu',        title: 'Adaptive Query Optimization Engine for Distributed Heterogeneous Database Management Systems', applicationNo: 'IN202241080234', filingDate: new Date('2022-08-12'), status: PatentStatus.PUBLISHED, inventors: ['Dr. Pramod Hegde'], country: 'India' },
    { facultyEmail: 'usha.venkat@college.edu',         title: 'Non-Invasive Continuous Glucose Monitoring System Using Near-Infrared Spectroscopy and ML', applicationNo: 'IN202141065678', patentNo: 'IN387654', filingDate: new Date('2021-11-08'), grantDate: new Date('2023-05-25'), status: PatentStatus.GRANTED, inventors: ['Dr. Usha Venkat'], country: 'India' },
    { facultyEmail: 'girish.nanda@college.edu',        title: 'Variable Stiffness Suspension System for Electric Vehicles with Active Vibration Damping', applicationNo: 'IN202241081345', filingDate: new Date('2022-09-25'), status: PatentStatus.PUBLISHED, inventors: ['Prof. Girish Nanda','Prof. Ashok Patel'], country: 'India' },
    { facultyEmail: 'arun.kumar@college.edu',          title: 'Lightweight Protocol for Secure Data Aggregation in Heterogeneous IoT Edge Networks', applicationNo: 'IN202341093456', filingDate: new Date('2023-05-30'), status: PatentStatus.FILED, inventors: ['Dr. Arun Kumar','Prof. Anita Desai'], country: 'India' },
    { facultyEmail: 'rekha.pandey@college.edu',        title: 'Intent-Based Network Management System with ML-Driven Policy Translation and Enforcement', applicationNo: 'IN202341098901', filingDate: new Date('2023-10-10'), status: PatentStatus.FILED, inventors: ['Dr. Rekha Pandey'], country: 'India' },
    { facultyEmail: 'deepa.krishnan@college.edu',      title: 'Real-Time Anomaly Detection Framework for Industrial IoT Using Edge-Cloud Hybrid Architecture', applicationNo: 'IN202241084567', filingDate: new Date('2022-07-14'), status: PatentStatus.PUBLISHED, inventors: ['Dr. Deepa Krishnan','Dr. Arun Kumar'], country: 'India' },
    { facultyEmail: 'sneha.gupta@college.edu',         title: 'Multilingual Sentiment Analysis System Using Cross-Lingual Transfer Learning for Indian Languages', applicationNo: 'IN202341099012', filingDate: new Date('2023-11-01'), status: PatentStatus.FILED, inventors: ['Prof. Sneha Gupta'], country: 'India' },
    { facultyEmail: 'leela.narayan@college.edu',       title: 'Ground Improvement Technique Using Nano-Cement Grouting for Liquefaction Susceptible Soils', applicationNo: 'IN202141069012', filingDate: new Date('2021-10-03'), status: PatentStatus.PUBLISHED, inventors: ['Prof. Leela Narayan'], country: 'India' },
    { facultyEmail: 'devraj.malhotra@college.edu',     title: 'Automated Technical Debt Detection and Prioritization Tool for Microservices Architecture', applicationNo: 'IN202341091345', filingDate: new Date('2023-04-18'), status: PatentStatus.FILED, inventors: ['Dr. Devraj Malhotra'], country: 'India' },
    { facultyEmail: 'esha.kulkarni@college.edu',       title: 'Adaptive Accessibility Layer for Mobile Applications Serving Users with Visual and Motor Impairments', applicationNo: 'IN202341095012', filingDate: new Date('2023-07-07'), status: PatentStatus.FILED, inventors: ['Prof. Esha Kulkarni','Prof. Sneha Gupta'], country: 'India' },
    { facultyEmail: 'naresh.joshi@college.edu',        title: 'Solar Powered Electrochemical Disinfection Unit for Rural Drinking Water Treatment', applicationNo: 'IN202041039012', patentNo: 'IN362345', filingDate: new Date('2020-10-20'), grantDate: new Date('2023-01-10'), status: PatentStatus.GRANTED, inventors: ['Dr. Naresh Joshi','Dr. Rajiv Sharma'], country: 'India' },
    { facultyEmail: 'vikram.singh@college.edu',        title: 'Self-Compacting Concrete Mix with Industrial Byproducts for Sustainable Construction', applicationNo: 'IN202241085678', filingDate: new Date('2022-08-28'), status: PatentStatus.PUBLISHED, inventors: ['Dr. Vikram Singh','Prof. Leela Narayan'], country: 'India' },
    { facultyEmail: 'arjun.mehta@college.edu',         title: 'Privacy-Preserving Federated Learning Protocol for Collaborative Medical Diagnosis', applicationNo: 'IN202341092456', filingDate: new Date('2023-06-06'), status: PatentStatus.FILED, inventors: ['Dr. Arjun Mehta'], country: 'India' },
    { facultyEmail: 'priya.nair@college.edu',          title: 'Smart Grid Metering IC with Built-In Tamper Detection and AES-256 Encryption', applicationNo: 'IN202341099123', filingDate: new Date('2023-09-19'), status: PatentStatus.FILED, inventors: ['Dr. Priya Nair','Dr. Aarti Saxena'], country: 'India' },
    { facultyEmail: 'suresh.rao@college.edu',          title: 'Hybrid Absorption-Compression Refrigeration System Powered by Low-Grade Waste Heat', applicationNo: 'IN202141070123', filingDate: new Date('2021-12-22'), status: PatentStatus.PUBLISHED, inventors: ['Prof. Suresh Rao'], country: 'India' },
  ];

  for (const patent of patents) {
    const faculty = byEmail[patent.facultyEmail];
    if (!faculty) continue;
    const { facultyEmail, ...rest } = patent;
    await prisma.patent.create({ data: { facultyId: faculty.id, ...rest } });
  }

  console.log(`  ✅ Patents seeded: ${patents.length} patents`);
}
