import { PrismaClient, ProjectStatus } from '@prisma/client';

export async function seedProjects(prisma: PrismaClient): Promise<void> {
  console.log('  🌱 Seeding funded projects...');

  const allFaculty = await prisma.facultyProfile.findMany({ include: { user: true } });
  const byEmail = Object.fromEntries(allFaculty.map(f => [f.user.email, f]));

  const projects = [
    { facultyEmail: 'arjun.mehta@college.edu',        title: 'Development of Privacy-Preserving Federated Learning Framework for Healthcare Diagnostics', fundingAgency: 'DST', scheme: 'SERB Core Research Grant', sanctionedAmount: 4200000, startDate: new Date('2023-01-01'), endDate: new Date('2026-01-01'), status: ProjectStatus.ONGOING, coInvestigators: ['Dr. Deepa Krishnan','Dr. Lavanya Subramanian'], description: 'Developing federated ML models for multi-institutional medical AI collaboration.' },
    { facultyEmail: 'priya.nair@college.edu',          title: 'Design of Ultra-Low Power VLSI Architectures for Wearable IoT Healthcare Devices', fundingAgency: 'AICTE', scheme: 'Research Promotion Scheme (RPS)', sanctionedAmount: 1500000, startDate: new Date('2022-04-01'), endDate: new Date('2024-03-31'), status: ProjectStatus.ONGOING, coInvestigators: ['Dr. Meena Iyer'] },
    { facultyEmail: 'suresh.rao@college.edu',          title: 'Experimental Investigation on Thermal Performance of Solar Parabolic Trough Collector with Hybrid Nanofluids', fundingAgency: 'MNRE', scheme: 'Solar Energy Research Initiative', sanctionedAmount: 2800000, startDate: new Date('2021-07-01'), endDate: new Date('2024-06-30'), status: ProjectStatus.ONGOING, coInvestigators: ['Prof. Ashok Patel'] },
    { facultyEmail: 'rajiv.sharma@college.edu',        title: 'AI-Based Optimal Power Flow Management in Smart Grid with Large-Scale Renewable Integration', fundingAgency: 'SERB', scheme: 'Power Electronics and Power Systems (PEPS)', sanctionedAmount: 5600000, startDate: new Date('2022-01-01'), endDate: new Date('2025-12-31'), status: ProjectStatus.ONGOING, coInvestigators: ['Prof. Divya Menon','Dr. Ravi Varma'] },
    { facultyEmail: 'anita.desai@college.edu',         title: 'Blockchain and AI-Enabled Cybersecurity Framework for Critical National Infrastructure', fundingAgency: 'MeitY', scheme: 'R&D in Cyber Security', sanctionedAmount: 3800000, startDate: new Date('2023-03-01'), endDate: new Date('2026-02-28'), status: ProjectStatus.ONGOING, coInvestigators: ['Dr. Rekha Pandey','Dr. Dilip Shetty'] },
    { facultyEmail: 'vikram.singh@college.edu',        title: 'Seismic Vulnerability Assessment and Retrofitting of Existing RC Buildings in Seismic Zone V', fundingAgency: 'NDMA', scheme: 'Earthquake Risk Reduction Programme', sanctionedAmount: 2500000, startDate: new Date('2021-06-01'), endDate: new Date('2023-05-31'), status: ProjectStatus.COMPLETED, coInvestigators: ['Prof. Leela Narayan'] },
    { facultyEmail: 'meena.iyer@college.edu',          title: 'Machine Learning Based Beamforming and Spectrum Management for 5G Millimeter Wave Networks', fundingAgency: 'DOT', scheme: 'Telecom Research Grant', sanctionedAmount: 1800000, startDate: new Date('2022-10-01'), endDate: new Date('2025-09-30'), status: ProjectStatus.ONGOING, coInvestigators: ['Dr. Chitra Suresh'] },
    { facultyEmail: 'ashok.patel@college.edu',         title: 'Sustainable Manufacturing Using Dry and Near-Dry Machining for Aerospace Alloys', fundingAgency: 'DST', scheme: 'Technology Mission for Advanced Manufacturing', sanctionedAmount: 3200000, startDate: new Date('2020-09-01'), endDate: new Date('2023-08-31'), status: ProjectStatus.COMPLETED, coInvestigators: ['Prof. Girish Nanda'] },
    { facultyEmail: 'lavanya.subramanian@college.edu', title: 'Developing Intelligent Collaborative Robots for Agri-Tech Applications in India', fundingAgency: 'DBT', scheme: 'Bioscience & Technology for Rural Development', sanctionedAmount: 4500000, startDate: new Date('2023-04-01'), endDate: new Date('2027-03-31'), status: ProjectStatus.ONGOING, coInvestigators: ['Dr. Arjun Mehta'] },
    { facultyEmail: 'ravi.varma@college.edu',          title: 'Intelligent Building Automation System with Occupancy-Aware Multi-Zone HVAC Control', fundingAgency: 'BEE', scheme: 'National Mission for Enhanced Energy Efficiency', sanctionedAmount: 2100000, startDate: new Date('2021-10-01'), endDate: new Date('2024-09-30'), status: ProjectStatus.ONGOING },
    { facultyEmail: 'naresh.joshi@college.edu',        title: 'Integrated Constructed Wetlands for Decentralized Wastewater Treatment in Peri-Urban Areas', fundingAgency: 'CPCB', scheme: 'National Water Quality Improvement Programme', sanctionedAmount: 3100000, startDate: new Date('2022-06-01'), endDate: new Date('2025-05-31'), status: ProjectStatus.ONGOING },
    { facultyEmail: 'kavita.reddy@college.edu',        title: 'Metal Oxide Semiconductor Nanowire Arrays for High Sensitivity Multi-Gas Detection Chip', fundingAgency: 'DST', scheme: 'SERB National Science Fund', sanctionedAmount: 2700000, startDate: new Date('2021-01-01'), endDate: new Date('2024-12-31'), status: ProjectStatus.ONGOING },
    { facultyEmail: 'mohan.das@college.edu',           title: 'Development of Sustainable Hybrid Biocomposites from Agro-Waste Fibers for Structural Applications', fundingAgency: 'DST', scheme: 'Technology Development Programme', sanctionedAmount: 1900000, startDate: new Date('2022-07-01'), endDate: new Date('2025-06-30'), status: ProjectStatus.ONGOING },
    { facultyEmail: 'shantha.pillai@college.edu',      title: 'Design of Green and Energy-Efficient Data Center Architecture with Adaptive Workload Management', fundingAgency: 'MeitY', scheme: 'Cloud Computing Research', sanctionedAmount: 3400000, startDate: new Date('2021-04-01'), endDate: new Date('2024-03-31'), status: ProjectStatus.ONGOING, coInvestigators: ['Dr. Pramod Hegde'] },
    { facultyEmail: 'arun.kumar@college.edu',          title: 'Edge AI Platform for Precision Agriculture Using Multi-Modal IoT Sensing and Federated Learning', fundingAgency: 'ICAR', scheme: 'NAHEP Innovation Grant', sanctionedAmount: 1200000, startDate: new Date('2023-06-01'), endDate: new Date('2025-05-31'), status: ProjectStatus.SANCTIONED },
    { facultyEmail: 'divya.menon@college.edu',         title: 'High Efficiency WBG Semiconductor Based On-Board Charger for Ultra-Fast EV Charging Stations', fundingAgency: 'DST', scheme: 'National Electric Mobility Mission Plan (NEMMP)', sanctionedAmount: 4800000, startDate: new Date('2022-03-01'), endDate: new Date('2025-02-28'), status: ProjectStatus.ONGOING, coInvestigators: ['Dr. Rajiv Sharma'] },
    { facultyEmail: 'sanjay.bhatt@college.edu',        title: 'Long-Term Performance Evaluation of Modified Bituminous Pavements Under Real Traffic Loading', fundingAgency: 'NRRDA', scheme: 'Rural Roads Research Grant', sanctionedAmount: 2300000, startDate: new Date('2021-08-01'), endDate: new Date('2024-07-31'), status: ProjectStatus.ONGOING },
    { facultyEmail: 'rekha.pandey@college.edu',        title: 'Software-Defined Industrial Network Architecture for Industry 4.0 Smart Manufacturing', fundingAgency: 'SERB', scheme: 'Early Career Research Award', sanctionedAmount: 3500000, startDate: new Date('2022-11-01'), endDate: new Date('2025-10-31'), status: ProjectStatus.ONGOING },
    { facultyEmail: 'girish.nanda@college.edu',        title: 'Development of Lightweight Crashworthy Vehicle Body Structure Using Multi-Material Topology Optimization', fundingAgency: 'SIAM', scheme: 'Automotive Technology Research Fund', sanctionedAmount: 2600000, startDate: new Date('2020-04-01'), endDate: new Date('2022-03-31'), status: ProjectStatus.COMPLETED, coInvestigators: ['Prof. Bhaskar Rao'] },
    { facultyEmail: 'usha.venkat@college.edu',         title: 'AI-Enabled Point-of-Care Diagnostic Platform for Early Detection of Diabetic Retinopathy', fundingAgency: 'DBT', scheme: 'Bioengineering and Biodesign Initiative', sanctionedAmount: 4100000, startDate: new Date('2022-09-01'), endDate: new Date('2025-08-31'), status: ProjectStatus.ONGOING },
    { facultyEmail: 'aarti.saxena@college.edu',        title: 'Online Condition Monitoring System for HV Equipment Using Machine Learning Diagnostics', fundingAgency: 'CEA', scheme: 'Power Sector R&D Programme', sanctionedAmount: 2200000, startDate: new Date('2021-05-01'), endDate: new Date('2024-04-30'), status: ProjectStatus.ONGOING },
    { facultyEmail: 'bhaskar.rao@college.edu',         title: 'Additive Manufacturing of Patient-Specific Bone Implants Using Biocompatible Titanium Alloys', fundingAgency: 'DBT', scheme: 'Biomedical Devices and Technology Programme', sanctionedAmount: 3700000, startDate: new Date('2023-02-01'), endDate: new Date('2026-01-31'), status: ProjectStatus.ONGOING },
    { facultyEmail: 'chitra.suresh@college.edu',       title: 'Design of Electronically Steerable Phased Array Antenna System for Satellite Communications', fundingAgency: 'ISRO', scheme: 'Respond Programme', sanctionedAmount: 5200000, startDate: new Date('2021-11-01'), endDate: new Date('2024-10-31'), status: ProjectStatus.ONGOING },
    { facultyEmail: 'devraj.malhotra@college.edu',     title: 'Automated Software Quality Assurance Tool for Continuous Integration Pipelines Using AI', fundingAgency: 'NASSCOM', scheme: 'Industry Academia Initiative', sanctionedAmount: 1600000, startDate: new Date('2022-06-01'), endDate: new Date('2024-05-31'), status: ProjectStatus.ONGOING },
    { facultyEmail: 'esha.kulkarni@college.edu',       title: 'Universal Design Framework for Inclusive Mobile Health Applications for Elderly Users in India', fundingAgency: 'MoHFW', scheme: 'National Digital Health Mission Research Grant', sanctionedAmount: 1100000, startDate: new Date('2023-08-01'), endDate: new Date('2025-07-31'), status: ProjectStatus.SANCTIONED },
    { facultyEmail: 'dilip.shetty@college.edu',        title: 'Post-Quantum Cryptographic Algorithms for Secure Communication in Critical Infrastructure', fundingAgency: 'DRDO', scheme: 'Cybersecurity Research Programme', sanctionedAmount: 4600000, startDate: new Date('2022-12-01'), endDate: new Date('2026-11-30'), status: ProjectStatus.ONGOING },
    { facultyEmail: 'pramod.hegde@college.edu',        title: 'Intelligent Data Lake Architecture for Multi-Source Healthcare Data Integration and Analytics', fundingAgency: 'DST', scheme: 'Data Science Research', sanctionedAmount: 2900000, startDate: new Date('2021-09-01'), endDate: new Date('2024-08-31'), status: ProjectStatus.ONGOING },
    { facultyEmail: 'sneha.gupta@college.edu',         title: 'Multilingual Natural Language Processing for Automated Government Document Digitization', fundingAgency: 'MeitY', scheme: 'National Language Translation Mission (NLTM)', sanctionedAmount: 2000000, startDate: new Date('2023-01-01'), endDate: new Date('2025-12-31'), status: ProjectStatus.ONGOING },
    { facultyEmail: 'leela.narayan@college.edu',       title: 'Ground Improvement and Foundation Design for Infrastructure on Expansive Black Cotton Soil', fundingAgency: 'MNRE', scheme: 'Geotechnical Hazard Mitigation Grant', sanctionedAmount: 1700000, startDate: new Date('2022-04-01'), endDate: new Date('2024-03-31'), status: ProjectStatus.ONGOING },
    { facultyEmail: 'deepa.krishnan@college.edu',      title: 'Real-Time Big Data Analytics Platform for Smart City Traffic and Environment Monitoring', fundingAgency: 'MoHUA', scheme: 'Smart Cities Mission Innovation Grant', sanctionedAmount: 3600000, startDate: new Date('2022-08-01'), endDate: new Date('2025-07-31'), status: ProjectStatus.ONGOING, coInvestigators: ['Dr. Arun Kumar'] },
    { facultyEmail: 'suresh.rao@college.edu',          title: 'Solar-Assisted Adsorption Cooling System for Energy-Efficient Building Air Conditioning', fundingAgency: 'DST', scheme: 'Clean Energy Research Initiative', sanctionedAmount: 2400000, startDate: new Date('2020-07-01'), endDate: new Date('2022-06-30'), status: ProjectStatus.COMPLETED },
    { facultyEmail: 'rajiv.sharma@college.edu',        title: 'Multi-Level Energy Storage Integration for Frequency Regulation in Island Microgrids', fundingAgency: 'MNRE', scheme: 'Off-Grid and Decentralized Renewable Energy', sanctionedAmount: 3900000, startDate: new Date('2019-10-01'), endDate: new Date('2022-09-30'), status: ProjectStatus.COMPLETED },
    { facultyEmail: 'vikram.singh@college.edu',        title: 'Accelerated Bridge Construction Techniques Using Ultra-High Performance Concrete', fundingAgency: 'MORTH', scheme: 'National Highways Research Programme', sanctionedAmount: 4400000, startDate: new Date('2023-05-01'), endDate: new Date('2026-04-30'), status: ProjectStatus.SANCTIONED },
    { facultyEmail: 'kavita.reddy@college.edu',        title: 'Integration of Organic Photovoltaics with Building Materials for Energy Harvesting Facades', fundingAgency: 'MNRE', scheme: 'Grid-Connected Solar Power Projects', sanctionedAmount: 3300000, startDate: new Date('2023-07-01'), endDate: new Date('2026-06-30'), status: ProjectStatus.SANCTIONED },
    { facultyEmail: 'usha.venkat@college.edu',         title: 'Smart Wearable EEG-Based Brain-Computer Interface for Rehabilitation of Stroke Patients', fundingAgency: 'ICMR', scheme: 'Extramural Research in Biomedical Sciences', sanctionedAmount: 2800000, startDate: new Date('2021-03-01'), endDate: new Date('2024-02-28'), status: ProjectStatus.ONGOING, coInvestigators: ['Dr. Arjun Mehta'] },
  ];

  for (const project of projects) {
    const faculty = byEmail[project.facultyEmail];
    if (!faculty) continue;
    const { facultyEmail, ...rest } = project;
    await prisma.project.create({ data: { facultyId: faculty.id, ...rest } });
  }

  console.log(`  ✅ Projects seeded: ${projects.length} funded projects`);
}
